#!/usr/bin/env sh

# DECKY_LOADER_VERSION="$1"

DECKY_USER="$1"
DECKY_USER_HOME=$(getent passwd $DECKY_USER | cut -d: -f6)

DECKY_VAR_DATA="$DECKY_USER_HOME/.local/share/decky-loader"

if [[ "$2" == "start" ]]; then
	install -d -o $DECKY_USER "$DECKY_VAR_DATA"
	install -d -o $DECKY_USER "$DECKY_VAR_DATA/services" "$DECKY_VAR_DATA/plugins"
	install -Dm 755 "/usr/lib/decky-loader/PluginLoader" "$DECKY_VAR_DATA/services/PluginLoader"
	STEAM_DEBUGGING_FILE="$DECKY_USER_HOME/.steam/steam/.cef-enable-remote-debugging"
	[ -f "$STEAM_DEBUGGING_FILE" ] || touch "$STEAM_DEBUGGING_FILE"
	# echo "$DECKY_LOADER_VERSION" > "$DECKY_VAR_DATA/services/.loader.version"
	systemctl start decky-loader@${DECKY_USER}.service
fi

if [[ "$2" == "stop" ]]; then
	systemctl stop decky-loader@${DECKY_USER}.service
fi
